version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose the application on port 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_CONTAINER=db
      - DB_PORT=3306
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sd2-db
    depends_on:
      - db
      - websocket # Ensure the WebSocket server starts before the app
    networks:
      - app_network

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "websocket_server.js"] # Start the WebSocket server
    ports:
      - "8080:8080" # Expose the WebSocket server on port 8080
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sd2-db
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./sd2-db.sql:/docker-entrypoint-initdb.d/sd2-db.sql:ro # Correct the SQL file path
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
